# AI Market Share Analysis: Python Processing

This notebook loads the `market_impact` table from PostgreSQL, calculates % change for each metric, and exports a CSV used for the Power BI dashboard.

**Before running:** replace `YOUR_PASSWORD` and `YOUR_DATABASE` in the connection string with your own PostgreSQL details.

## 1. Install libraries

In [1]:
!pip install pandas psycopg2-binary sqlalchemy

## 2. Load data from PostgreSQL

In [3]:
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:YOUR_PASSWORD@localhost:5432/YOUR_DATABASE')

query = "SELECT * FROM market_impact;"
df = pd.read_sql(query,engine)
df

,id,company,product,metric_type,value_before,value_after,source
0,1,OpenAI,ChatGPT,Market Share %,76.4,62.6,SearchEngineJournal
1,2,Anthropic,Claude,Market Share %,8.9,18.5,SearchEngineJournal
2,3,Google,Gemini,Market Share %,9.0,27.3,SearchEngineJournal
3,4,Perplexity,Perplexity,Market Share %,3.5,7.3,First Page Sage
4,5,OpenAI,ChatGPT,Weekly Active Users (M),900.0,900.0,OpenAI Official
5,6,Google,Gemini,Monthly Active Users (M),500.0,1000.0,First Page Sage
6,7,Anthropic,Claude,Annual Revenue ($B),9.0,65.0,Reuters
7,8,OpenAI,GPT-6 Astra,Benchmark Score,0.0,53.0,Artificial Analysis Index
8,9,Anthropic,Claude Fable 5.1,Benchmark Score,0.0,53.0,Artificial Analysis Index

## 3. Calculate % change

Rows where `value_before` is 0 (new models in the benchmark score rows) are left empty, because % change cannot be calculated from zero.

In [6]:
df['percent_change']=df.apply(
    lambda row : round(((row['value_after'] - row['value_before'])/row['value_before'])*100,2)
    if row['value_before']!=0 else None,
    axis=1
)
df

,id,company,product,metric_type,value_before,value_after,source,percent_change
0,1,OpenAI,ChatGPT,Market Share %,76.4,62.6,SearchEngineJournal,-18.06
1,2,Anthropic,Claude,Market Share %,8.9,18.5,SearchEngineJournal,107.87
2,3,Google,Gemini,Market Share %,9.0,27.3,SearchEngineJournal,203.33
3,4,Perplexity,Perplexity,Market Share %,3.5,7.3,First Page Sage,108.57
4,5,OpenAI,ChatGPT,Weekly Active Users (M),900.0,900.0,OpenAI Official,0.00
5,6,Google,Gemini,Monthly Active Users (M),500.0,1000.0,First Page Sage,100.00
6,7,Anthropic,Claude,Annual Revenue ($B),9.0,65.0,Reuters,622.22
7,8,OpenAI,GPT-6 Astra,Benchmark Score,0.0,53.0,Artificial Analysis Index,NaN
8,9,Anthropic,Claude Fable 5.1,Benchmark Score,0.0,53.0,Artificial Analysis Index,NaN

## 4. Sort by % change

In [8]:
df_sorted = df.sort_values(by='percent_change', ascending = False)
df_sorted

,id,company,product,metric_type,value_before,value_after,source,percent_change
6,7,Anthropic,Claude,Annual Revenue ($B),9.0,65.0,Reuters,622.22
2,3,Google,Gemini,Market Share %,9.0,27.3,SearchEngineJournal,203.33
3,4,Perplexity,Perplexity,Market Share %,3.5,7.3,First Page Sage,108.57
1,2,Anthropic,Claude,Market Share %,8.9,18.5,SearchEngineJournal,107.87
5,6,Google,Gemini,Monthly Active Users (M),500.0,1000.0,First Page Sage,100.00
4,5,OpenAI,ChatGPT,Weekly Active Users (M),900.0,900.0,OpenAI Official,0.00
0,1,OpenAI,ChatGPT,Market Share %,76.4,62.6,SearchEngineJournal,-18.06
7,8,OpenAI,GPT-6 Astra,Benchmark Score,0.0,53.0,Artificial Analysis Index,NaN
8,9,Anthropic,Claude Fable 5.1,Benchmark Score,0.0,53.0,Artificial Analysis Index,NaN

## 5. Export CSV for Power BI

In [10]:
df.to_csv('ai_market_processed.csv',index=False)
print("CSV file saved successfully!")

CSV file saved successfully!

## 6. Highest % change

In [13]:
highest = df_sorted.iloc[0]
print(f"Highest % Change: {highest['company']} ({highest['product']}) - {highest['percent_change']}%")

Highest % Change: Anthropic (Claude) - 622.22%